In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("Crop_recommendation.csv")

In [4]:
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [5]:
df.shape

(2200, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [7]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [10]:
crop_dict = {
    'rice': 1,
    'maize': 2,
    'jute': 3,
    'cotton': 4,
    'coconut': 5,
    'papaya': 6,
    'orange': 7,
    'apple': 8,
    'muskmelon': 9,
    'watermelon': 10,
    'grapes': 11,
    'mango': 12,
    'banana': 13,
    'pomegranate': 14,
    'lentil': 15,
    'blackgram': 16,
    'mungbean': 17,
    'mothbeans': 18,
    'pigeonpeas': 19,
    'kidneybeans': 20,
    'chickpea': 21,
    'coffee': 22
}
df['crop_num']=df['label'].map(crop_dict)

In [11]:
df.head()

N   P   K  temperature   humidity        ph    rainfall label  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice         1
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice         1
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice         1
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice         1
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice         1

In [12]:
df['crop_num'].value_counts()

crop_num
1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
11    100
12    100
13    100
14    100
15    100
16    100
17    100
18    100
19    100
20    100
21    100
22    100
Name: count, dtype: int64

In [13]:
df.drop(['label'],axis=1,inplace=True)
df.head()

N   P   K  temperature   humidity        ph    rainfall  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536         1
1  85  58  41    21.770462  80.319644  7.038096  226.655537         1
2  60  55  44    23.004459  82.320763  7.840207  263.964248         1
3  74  35  40    26.491096  80.158363  6.980401  242.864034         1
4  78  42  42    20.130175  81.604873  7.628473  262.717340         1

In [14]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(df,df['crop_num']):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [15]:
strat_train_set['crop_num'].value_counts()

crop_num
17    80
8     80
5     80
18    80
20    80
13    80
9     80
22    80
21    80
12    80
19    80
3     80
1     80
16    80
6     80
15    80
11    80
2     80
7     80
14    80
10    80
4     80
Name: count, dtype: int64

In [16]:
train_feature = strat_train_set.drop("crop_num",axis=1)
train_label = strat_train_set["crop_num"].copy()

In [17]:
test_feature = strat_test_set.drop("crop_num",axis=1)
test_label = strat_test_set["crop_num"].copy()

In [18]:
train_feature.shape

(1760, 7)

In [19]:
test_feature.shape

(440, 7)

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [21]:
my_pipeline = Pipeline([
    ('std_scaler',StandardScaler())
    # we can add as we want in pipeline
])

In [22]:
train_feature = my_pipeline.fit_transform(train_feature)
test_feature = my_pipeline.fit_transform(test_feature)

In [23]:
train_feature

array([[-0.53417847, -0.06789696, -0.45715906, ...,  0.63108663,
         0.95211575, -0.91527645],
       [-1.02211959,  2.20913526,  3.07707053, ...,  0.95484645,
        -0.1053335 ,  0.08073056],
       [ 1.63444873, -1.43411629,  0.09568132, ...,  0.76645065,
        -0.19588187, -1.04085288],
       ...,
       [ 1.28204681, -1.40375586, -0.06227307, ...,  0.94204329,
        -0.39836382, -1.38768442],
       [ 0.87542921, -1.16087242,  0.01670413, ...,  0.89199793,
        -0.03407228, -1.45364806],
       [-1.13055095,  2.72526256,  2.93886044, ...,  0.95866808,
        -1.16221818,  0.25182973]])

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

# create instances of all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}

In [25]:
for name, md in models.items():
    md.fit(train_feature,train_label)
    y_pred = md.predict(test_feature)
    
    print(f"{name}  with accuracy : {accuracy_score(test_label,y_pred)}")

Logistic Regression  with accuracy : 0.9704545454545455
Naive Bayes  with accuracy : 0.9954545454545455
Support Vector Machine  with accuracy : 0.9795454545454545
K-Nearest Neighbors  with accuracy : 0.9795454545454545
Decision Tree  with accuracy : 0.9727272727272728
Random Forest  with accuracy : 0.9977272727272727
Bagging  with accuracy : 0.975


C:\Users\Dell\AppData\Roaming\Python\Python312\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoost  with accuracy : 0.18181818181818182
Gradient Boosting  with accuracy : 0.9863636363636363
Extra Trees  with accuracy : 0.9363636363636364


In [26]:
rfc = RandomForestClassifier()
rfc.fit(train_feature,train_label)
y_pred = rfc.predict(test_feature)
accuracy_score(test_label,y_pred)

0.9977272727272727

In [27]:
def recommendation(N,P,k,temperature,humidity,ph,rainfal):
    features = np.array([[N,P,k,temperature,humidity,ph,rainfal]])
    transformed_features = my_pipeline.fit_transform(features)
    prediction = rfc.predict(transformed_features)
    
    return prediction

In [28]:
N = 9
P = 4
k = 22
temperature = 25
humidity = 81
ph = 7
rainfall = 270

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)


# crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
#                  8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
#                  14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
#                  19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

# if predict[0] in crop_dict:
#     crop = crop_dict[predict[0]]
#     print("{} is a best crop to be cultivated ".format(crop))
# else:
#     print("Sorry are not able to recommend a proper crop for this environment")

predict

array([6], dtype=int64)

In [29]:
some_data = test_feature[:10]
some_label = test_label[:10]

In [30]:
some_label

609     17
172      2
1612     7
1100    12
645     17
1921     4
228     21
2001     3
197      2
638     17
Name: crop_num, dtype: int64

In [31]:
rfc.predict(some_data)

array([17,  2,  7, 12, 17,  4, 21,  3,  2, 17], dtype=int64)

In [67]:
rfc.predict([[90,40,43,21,82,6,202]])

array([8], dtype=int64)

In [69]:
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score, accuracy_score,roc_curve,roc_auc_score

In [71]:
print(classification_report(test_label, y_pred))

              precision    recall  f1-score   support

           1       0.95      1.00      0.98        20
           2       1.00      1.00      1.00        20
           3       1.00      0.95      0.97        20
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20
           6       1.00      1.00      1.00        20
           7       1.00      1.00      1.00        20
           8       1.00      1.00      1.00        20
           9       1.00      1.00      1.00        20
          10       1.00      1.00      1.00        20
          11       1.00      1.00      1.00        20
          12       1.00      1.00      1.00        20
          13       1.00      1.00      1.00        20
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        20
          16       1.00      1.00      1.00        20
          17       1.00      1.00      1.00        20
          18       1.00    